version: '3.5'

services:

  cli:
    image: srijanlabs/php-cli:7.3-1.x-dev
    user: continua
    command: ["composer", "install", "--no-dev", "--prefer-dist", "--no-progress", "--no-suggest", "--no-interaction", "--optimize-autoloader"]
    working_dir: /app
    volumes:
      - app:/app
    networks: 
      - continua-demo

  drupal:
    image: srijanlabs/php-fpm-apache:7.3-1.x
    depends_on:
      - cli
      - db
    command: ["start.sh"]
    ports:
      - 9000:9000
      - 8080:8080
    volumes:
      - ./apache/vhost/app.conf:/etc/apache2/sites-enabled/000-default.conf 
      - app:/app
    # env_file: 
    #   - .db-env
    networks: 
     - continua-demo
  
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vega
      MYSQL_USER: vega
      MYSQL_PASSWORD: vega
      MYSQL_DATABASE: vega
    networks: 
     - continua-demo

volumes:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
  data:

networks:
  continua-demo:
